### ISSUE TITLE
NullPointerException when DATE field is null

### ISSUE THREAD

**Issue by cristian-p** [finsoft-java/teradataExport#1]
A "NullPointerException" is thrown if the resultset contains a null value DATE column.

`Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NullPointerException
        at java.util.Calendar.setTime(Calendar.java:1770)
        at java.text.SimpleDateFormat.format(SimpleDateFormat.java:943)
        at java.text.SimpleDateFormat.format(SimpleDateFormat.java:936)
        at java.text.DateFormat.format(DateFormat.java:345)
        at it.finsoft.TeradataExport.formattaCampo(TeradataExport.java:108)
        at it.finsoft.TeradataExport.main(TeradataExport.java:42)
        ... 5 more`

**Comment by cristian-p** [comment]
Tried moving 
`dataFinale = formatter.format(rs.getDate(i));`

after the null check:

`if (rs.getString(i) != null) {
			dataFinale = formatter.format(rs.getDate(i));
			part2Insert.append("'" + dataFinale + "'");
			} else....`

to avoid the error, seems to work.
